---
name: build-go

on:
  - push

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'

      - name: Download Go dependencies
        run: go mod download

      - name: test
        run: |
          go test ./...
