---
name: build-go

on:
  - push

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Check out source code
        uses: actions/checkout@v3

      - name: Download Go dependencies
        run: go mod download

      - name: test
        run: |
          go test ./...
